### ISSUE TITLE
Contribution by others

### ISSUE THREAD

**Issue by bharadwajpro** [GiVoTa/fcc-html#1]
Can users contribute to this repo or is it your presonal repo ?

**Comment by GiVoTa** [comment]
I haven't really thought about it.
I guess I have meant this to be a repo for my excercises, but I don't see a problem with other users also contributing here and/or reviewing my code.

Everyone is welcome.

**Comment by bharadwajpro** [comment]
Can users add other exercise solutions of fcc which are not listed here ?(There are future exercises about bootstrap, jquery etc)

**Comment by GiVoTa** [comment]
Yes, I'm fine with that as well.
Obviously, everyone has their own progression speed.
Once I get past these myself, I might take a peek to see how others have handled them (when an excercise gives some freedom to do so, that is). Of course, only with the permit of the creator of the commit.

**Comment by bharadwajpro** [comment]
Thank you. I too wanted the code I had written to be at one place. Since you have already added a repo for this, I thought of adding my code to the repo. I may add some pull requests soon.

**Comment by GiVoTa** [comment]
Go for it! You're welcome to use it as you wish

**Comment by GiVoTa** [comment]
Since I've set you as a collaborator, I'm feeling free to close this issue.
